server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: your-client-id
            client-secret: your-client-secret
            authorization-grant-type: client_credentials
            scope: https://storage.azure.com/.default
        provider:
          azure:
            token-uri: https://login.microsoftonline.com/your-tenant-id/oauth2/v2.0/token

azure:
  storage:
    account-name: your-storage-account
    container-name: your-container
